### ISSUE TITLE
Perception restriction of inner walls

### ISSUE THREAD

**Issue by Tupsi** [EwoudLindemans/FoundryVTT-Modules-Radugen#59]
I was playing around with lighting in a created dungeon and noticed that there are two types of walls created, the outer with "normal" perception restriction and the inner with "none". This leads to light flowing where it should (through the inner walls). I was wondering, if this is intentional or not and if it could be changed if its not intentional.

The idea is that actors moving around with nothing but a light source one them can only see what their own light would be able to travel to.

It only effects the inner part of the map where intersections meet each other, as the their seems to be no space left for another outer walls, so these walls are just made of of inner walls.
![actorview](https://user-images.githubusercontent.com/3730499/107579555-98398c80-6bf5-11eb-9d73-03c752036950.jpg)
![gmview](https://user-images.githubusercontent.com/3730499/107579561-9a9be680-6bf5-11eb-903a-da930aa9f0d9.jpg)

**Comment by StefanWouters** [comment]
Thank you for trying out Radugen. :-)
We are preparing to add a setting so you can switch between 'strict' walls and the current mode.
I believe the code is already halfway there... so it might be available in our next release.

**Comment by Tupsi** [comment]
ahh cool, thanks. I also put up some picture in case my wall of text wasnt clear what I ment. Another approach would also be to leave enough room in the inner section, so you can always draw "outer walls" even there. That would kill the problem nicely as well.
