### ISSUE TITLE
Dungen  Generate button does not generate a dungeon in OSE and Radugen v0.0.2

### ISSUE THREAD

**Issue by mccaffertyt** [EwoudLindemans/FoundryVTT-Modules-Radugen#63]
Works in OSE with Radugen v0.0.1

**Comment by StefanWouters** [comment]
Hi, thank you for trying Radugen. Did you get a generate dungeon dialogue? Did you try different settings? Could you check the browser Dev tools (F12 key) to see if there are any console errors? Thank you very much!

**Comment by mccaffertyt** [comment]
Hi Stefan

No I did not get a dungeon dialogue. I am going to try v0.0.2 with DND 3.5 and see if that works.

Also on removing the module it deletes the uploads\scenes folder so any previously generated dungeons are lost. (not in recycle bin).

Thanks

Tom

**Comment by mccaffertyt** [comment]
Also does not work with Simple World Builder or D$D 3.3e SRD.

**Comment by EwoudLindemans** [comment]
Hi mccafferty.

I have created a new release that should fix the issue's that we had with 0.0.2
Could you try out 0.0.3?

**Comment by EwoudLindemans** [comment]
To get back to you on the removing the module, and it deletes the uploads\scenes folder, You can pick your own folder to upload to. It can be changed in the module settings.

**Comment by mccaffertyt** [comment]
Hi Radugen Team

Thanks for the excellent support. I have tried out v0.0.3 and all is well.

I have redirected my default upload directory and now should be safe from future deletions.

Cheers

Tom
