### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by HippyCraig** [EwoudLindemans/FoundryVTT-Modules-Radugen#68]
So I installed the mod and tried to create two scenes, I got warnings that its storing image files in the mod directory by default, I can see where to change that value, but that seems like an odd place for a default.  

But after creating I do not see the scene added to my list, is this tool supposed to auto generate the scene and walls?  If so how do I add that into my world?

**Comment by HippyCraig** [comment]
I'll give that a try, did it still use the default location for storing those files or did you change them

**Comment by dirkvandooren** [comment]
No same location. I did see the ones that I made before also there, but they weren't picked up by the compendium, Not sure what i'll do if/when I upgrade the plugin.

**Comment by EwoudLindemans** [comment]
Hey, 

Im gonna look into this issue, I got more reports about this problem, coming back asap :)

**Comment by EwoudLindemans** [comment]
Fixed in 0.0.5 Release
